### ISSUE TITLE
[FEAT] user 정보를 불러와 User Model 에 저장하기

### ISSUE THREAD

**Issue by Genesis2010** [G-3280/iOS_SwiftUI#21]
## 💡 Issue
- Firebase Firestore 에 저장된 해당 User 정보를 불러오는 기능을 구현

## 📝  todo
- [x] User Model 구현
- [x] FireStore 의 users 컬렉션에 해당하는 uid 를 찾아 내용을 model 에 저장
- [x] 로그인시 Auth 와 Firestore 에 정보가 있는지 확인 후 로그인
