### ISSUE TITLE
[FEAT] 카테고리에 맞는 Mission 및 현재 날짜 출력 기능 구현

### ISSUE THREAD

**Issue by Genesis2010** [G-3280/iOS_SwiftUI#25]
## 💡 Issue
- 하단 List 에 선택된 카테고리에 맞는 Mission 을 출력하게 만듭니다
- 현재 날짜를 보여주는 상단 Text 를 현재 시간에 맞게 조정합니다

## 📝  todo
- [x] MissionView 에 있는 날짜를 현재 날짜로 변경
- [x] 일일미션, 주간미션에 해당하는 미션을 출력하게 변경
- [x] 두번째 옵션 카테고리에 맞게 미션을 출력하게 변경
