### ISSUE TITLE
[FEAT] 캐릭터 디테일 뷰 , 평가 진행 뷰 구현

### ISSUE THREAD

**Issue by hxxlxn-Kxxx** [G-3280/iOS_SwiftUI#30]
## 💡 Issue
- 캐릭터 디테일 뷰 : 캐릭터 카드 선택 시 뜨는 화면으로, 캐릭터에 대한 자세한 설명을 보여줌
- 평가 진행 뷰 : 다른 사람의 미션 완료 인증 사진을 보고 평가함
- 평가 완료 뷰 : 평가를 다 마친 후 뜨는 화면. 홈으로 돌아감.

## 📝  todo
- [x] 캐릭터 디테일 뷰 구현
- [x] 평가 진행 뷰 구현
- [x] 평가 완료 뷰 구현
